### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Ardaa001** [pooooooon/JavaPlayer#6]
string(5) "ok754"

Fatal error: Declaration of pooooooon\javaplayer\network\JavaPlayerNetworkSession::addToSendBuffer(pocketmine\network\mcpe\protocol\ClientboundPacket $packet): void must be compatible with pocketmine\network\mcpe\NetworkSession::addToSendBuffer(string $buffer): void in C:\Users\Administrator\Desktop\test\plugins\JavaPlayer-1.16.5\src\pooooooon\JavaPlayer\network\JavaPlayerNetworkSession.php on line 139

**Comment by encyptAES** [comment]
i will fix it soon

**Comment by encyptAES** [comment]
> 

you are using old version of this plugin pls update
